version: '3'
services:
  auth:
    build:
      context: .
      dockerfile: ./deployment/docker/Dockerfile
    container_name: auth
    image: crdschurch/crds-service-auth:${DOCKER_TAG:-local}
    env_file:
      - .env
    ports:
      - "5000:80"
  cypress:
    build: ./Crossroads.Service.Auth.IntegrationTest
    container_name: cypress
    image: cypress/base:8
    restart: on-failure
    depends_on:
      - auth
    environment:
      - CYPRESS_baseUrl=http://auth #This must be a fully qualified domain name
    command: ./wait-for-it.sh auth:80 -- npx cypress run