version: '3'
services:
  auth:
    build:
      context: .
      dockerfile: ./deployment/docker/Dockerfile
    container_name: auth
    image: crdschurch/crds-service-auth:${DOCKER_TAG:-local}
    environment:
      - VAULT_ROLE_ID=${VAULT_ROLE_ID}
      - VAULT_SECRET_ID=${VAULT_SECRET_ID}
      - CRDS_ENV=${CRDS_ENV}
    ports:
      - "5000:80"
  cypress_auth:
    build: ./Crossroads.Service.Auth.IntegrationTest
    container_name: cypress_auth
    image: cypress/included:3.2.0
    depends_on:
      - auth
    environment:
      - CYPRESS_baseUrl=http://auth #This must be a fully qualified domain name
      - CYPRESS_VAULT_ROLE_ID=${VAULT_ROLE_ID}
      - CYPRESS_VAULT_SECRET_ID=${VAULT_SECRET_ID}
      - CYPRESS_CRDS_ENV=${CRDS_ENV}
    working_dir: /cypress-service-auth
    command: /cypress-service-auth/wait-for-it.sh auth:80 -- npx cypress run