apiVersion: extensions/v1beta1 
kind: Deployment 
metadata: 
  name: crds-auth
  namespace: api
spec: 
  replicas: 2
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 2
      maxUnavailable: 0 
  template: 
    metadata: 
      labels:
        app: crds-auth
    spec: 
      containers: 
        - name: crds-auth
          image: crdschurch/crds-service-auth:$DOCKER_TAG
          imagePullPolicy: Always 
          ports: 
            - containerPort: 80 
          resources: 
            limits: 
              memory: "1Gi"
              cpu: "500m" 
            requests: 
              memory: "16Mi" 
              cpu: "100m" 
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 3
            successThreshold: 1
            periodSeconds: 10
          env: 
            - name: ASPNETCORE_ENVIRONMENT
              value: $ASPNETCORE_ENVIRONMENT
            - name: MP_OAUTH_BASE_URL
              value: $MP_OAUTH_BASE_URL
            - name: OKTA_OAUTH_BASE_URL
              value: $OKTA_OAUTH_BASE_URL
            - name: NEW_RELIC_LICENSE_KEY            
              value: $NR_INSTALL_KEY
            - name: NEW_RELIC_APP_NAME
              value: $NR_APP_NAME
            - name: LOGZ_IO_KEY
              value: $LOGZ_IO_KEY
            - name: APP_NAME
              value: $APP_NAME
            - name: CRDS_MP_COMMON_CLIENT_ID
              value: $CRDS_MP_COMMON_CLIENT_ID
            - name: CRDS_MP_COMMON_CLIENT_SECRET
              value: $CRDS_MP_COMMON_CLIENT_SECRET
            - name: CRDS_GATEWAY_CLIENT_ENDPOINT
              value: $CRDS_GATEWAY_CLIENT_ENDPOINT