apiVersion: extensions/v1beta1 
kind: Deployment 
metadata: 
  name: crds-auth
  namespace: api
spec: 
  replicas: 2
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 2
      maxUnavailable: 0
  template: 
    metadata: 
      labels:
        app: crds-auth
    spec: 
      containers: 
        - name: crds-auth
          image: crdschurch/crds-service-auth:$DOCKER_TAG
          imagePullPolicy: Always 
          ports: 
            - containerPort: 80
          resources: 
            limits: 
              memory: "1Gi"
              cpu: "500m"
            requests: 
              memory: "16Mi" 
              cpu: "100m" 
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 3
            successThreshold: 1
            periodSeconds: 10
          env: 
            - name: MP_OAUTH_BASE_URL
              value: $MP_OAUTH_BASE_URL
            - name: NEW_RELIC_LICENSE_KEY            
              value: $NR_INSTALL_KEY
            - name: NEW_RELIC_APP_NAME
              value: $NR_APP_NAME
            - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
              value: $NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
            - name: CRDS_MP_COMMON_CLIENT_ID
              value: $CRDS_MP_COMMON_CLIENT_ID
            - name: CRDS_MP_COMMON_CLIENT_SECRET
              value: $CRDS_MP_COMMON_CLIENT_SECRET
            - name: MP_REST_API_ENDPOINT
              value: $MP_REST_API_ENDPOINT
            - name: CRDS_ENV
              value: $CRDS_ENV
            - name: VAULT_ROLE_ID
              value: $VAULT_ROLE_ID
            - name: VAULT_SECRET_ID
              value: $VAULT_SECRET_ID