apiVersion: v1 
kind: Service 
metadata: 
  name: crds-auth-service
  namespace: api
  labels: 
    app: crds-auth-service
spec:
  type: NodePort
  ports: 
  - name: dotnet 
    port: 80
    targetPort: 80 
  selector: 
    app: crds-auth