version: '3'
services:
  auth:
    build:
      context: ../../ 
      dockerfile: ./deployment/docker/Dockerfile
    container_name: auth
    image: crdschurch/crds-service-auth:${DOCKER_TAG:-local}
    environment:
      - VAULT_ROLE_ID=${VAULT_ROLE_ID}
      - VAULT_SECRET_ID=${VAULT_SECRET_ID}
      - CRDS_ENV=${CRDS_ENV}
  integration_tests:
    build:
      context: ../../ 
      dockerfile: ./deployment/docker-integration-tests/Dockerfile
    container_name: cypress_auth_integration
    image: crdschurch/crds-service-auth-integration:${DOCKER_TAG:-local}
    ipc: host # Cypress workaround for render crashes in docker
    depends_on:
      - auth
    environment:
      - CYPRESS_baseUrl=http://auth #This must be a fully qualified domain name
      - CYPRESS_vaultEnv=${CRDS_ENV}
      - VAULT_ROLE_ID=${VAULT_ROLE_ID}
      - VAULT_SECRET_ID=${VAULT_SECRET_ID}
      - CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY} #Report to Cypress Dashboard. Required when the --record and --tag flag are used.

    # Use this command to report results to the Cypress Dashboard. Only recommended if running in CI pipeline.
    command: [ "--record", "--tag", "$CRDS_ENV" ]