version: '3'
services:
  auth:
    build:
      context: ../../ 
      dockerfile: ./deployment/docker/Dockerfile
    container_name: auth
    image: crdschurch/crds-service-auth:${DOCKER_TAG:-local}
    environment:
      - VAULT_ROLE_ID=${VAULT_ROLE_ID}
      - VAULT_SECRET_ID=${VAULT_SECRET_ID}
      - CRDS_ENV=${CRDS_ENV}
    ports:
      - "5000:80"
  integration_tests:
    build:
      context: ../../ 
      dockerfile: ./deployment/docker-integration-tests/Dockerfile
    container_name: cypress_auth_integration
    image: crdschurch/crds-service-auth-integration:${DOCKER_TAG:-local}
    depends_on:
      - auth
    environment:
      - CYPRESS_baseUrl=http://auth #This must be a fully qualified domain name
      - CYPRESS_vaultEnv=${CRDS_ENV}
      - VAULT_ROLE_ID=${VAULT_ROLE_ID}
      - VAULT_SECRET_ID=${VAULT_SECRET_ID}
      