version: '3' 
services: 
  CrossroadsServiceAuth: 
    build: 
      context: ../../ 
      dockerfile: ./deployment/docker/Dockerfile
    container_name: crds-service-auth
    image: crdschurch/crds-service-auth:${DOCKER_TAG:-local} 
    # env_file:
    #   - ../../.env
    ports:
      - "5000:80"